// Most App — Polish Language Strings
export const PL = {
  app: {
    name: 'Most',
    tagline: 'Buduj mosty, nie mury',
    taglineSub: 'Rozwiązuj konflikty razem',
  },
  onboarding: {
    slide1Title: 'Rozmawiaj bezpiecznie',
    slide1Sub: 'Most tworzy przestrzeń, gdzie oboje możecie wyrazić swoje uczucia bez oceniania.',
    slide2Title: 'Zrozumcie się nawzajem',
    slide2Sub: 'Faza lustra pomaga partnerowi zobaczyć Twój punkt widzenia i potwierdzić zrozumienie.',
    slide3Title: 'Znajdźcie rozwiązanie',
    slide3Sub: 'AI mediator prowadzi Was przez 4 fazy do wspólnego, trwałego rozwiązania.',
    begin: 'Zacznij teraz',
    login: 'Mam już konto',
  },
  auth: {
    loginTitle: 'Zaloguj się',
    loginSub: 'Wróć do swojego partnera',
    registerTitle: 'Utwórz konto',
    registerSub: 'Zacznij budować mosty',
    email: 'Adres e-mail',
    password: 'Hasło',
    name: 'Imię',
    loginBtn: 'Zaloguj się',
    registerBtn: 'Utwórz konto',
    withGoogle: 'Kontynuuj z Google',
    noAccount: 'Nie masz konta?',
    hasAccount: 'Masz już konto?',
    register: 'Zarejestruj się',
    login: 'Zaloguj się',
    orWith: 'lub',
    forgotPassword: 'Zapomniałeś hasła?',
  },
  couple: {
    connectTitle: 'Połącz się z partnerem',
    connectSub: 'Zaproś partnera kodem lub wpisz jego kod zaproszenia.',
    myCode: 'Twój kod zaproszenia',
    enterCode: 'Wpisz kod partnera',
    connect: 'Połącz się',
    copy: 'Kopiuj',
    copied: 'Skopiowano!',
    share: 'Udostępnij',
    partner: 'Partner',
    connected: 'Połączeni',
    connectedSince: 'Razem od',
    waiting: 'Oczekiwanie na partnera...',
    inviteSent: 'Zaproszenie wysłane',
  },
  dispute: {
    newDispute: 'Nowy spór',
    newDisputeBtn: '+ Nowy spór',
    title: 'Temat sporu',
    titlePlaceholder: 'Np. "Podział obowiązków domowych"',
    description: 'Opisz sytuację',
    descPlaceholder: 'Co się wydarzyło? Jak się czujesz?',
    startDispute: 'Rozpocznij spór',
    activeDisputes: 'Aktywne spory',
    resolvedDisputes: 'Rozwiązane spory',
    noDisputes: 'Brak aktywnych sporów',
    noDisputesSub: 'Świetnie! Zacznij nowy spór jeśli chcesz coś omówić.',
    noResolved: 'Brak rozwiązanych sporów',
    noResolvedSub: 'Rozwiązane spory pojawią się tutaj.',
    limitReached: 'Osiągnąłeś limit',
    limitSub: 'Plan Free pozwala na 3 spory miesięcznie. Przejdź na Premium.',
    upgrade: 'Przejdź na Premium',
    phase: 'Faza',
    of: 'z',
    waitingPartner: 'Oczekiwanie na partnera',
    yourTurn: 'Twoja kolej',
    bothReady: 'Oboje gotowi',
    resolved: 'Rozwiązany',
    createdAt: 'Utworzono',
    disputeOf: 'Spór o',
  },
  phases: {
    phase1Name: 'Indywidualnie',
    phase1Desc: 'Opisz sytuację ze swojej perspektywy',
    phase1Icon: 'person',
    phase2Name: 'Lustro',
    phase2Desc: 'Potwierdź zrozumienie punktu widzenia partnera',
    phase2Icon: 'flip',
    phase3Name: 'Razem',
    phase3Desc: 'Omówcie sytuację wspólnie',
    phase3Icon: 'people',
    phase4Name: 'Rozwiązanie',
    phase4Desc: 'Ustalcie wspólne rozwiązanie',
    phase4Icon: 'handshake',
    myPerspective: 'Moja perspektywa',
    myPerspectivePlaceholder: 'Opisz jak widzisz tę sytuację. Co czujesz? Co jest dla Ciebie ważne?',
    feelings: 'Moje uczucia',
    feelingsPlaceholder: 'Np. czuję się zignorowany/a, sfrustrowany/a...',
    needs: 'Czego potrzebuję',
    needsPlaceholder: 'Np. potrzebuję więcej uznania, lepszej komunikacji...',
    mirrorTitle: 'Perspektywa partnera',
    mirrorPrompt: 'Twój partner powiedział:',
    mirrorConfirm: 'Potwierdzam, że rozumiem',
    mirrorResponse: 'Moja odpowiedź (opcjonalnie)',
    mirrorResponsePlaceholder: 'Możesz dodać komentarz...',
    jointMessage: 'Wiadomość do partnera',
    jointMessagePlaceholder: 'Napisz coś do partnera w tej fazie...',
    resolutionTitle: 'Propozycja rozwiązania',
    resolutionPlaceholder: 'Jakie rozwiązanie proponujesz?',
    agreeResolution: 'Akceptuję to rozwiązanie',
    disagreeResolution: 'Proponuję inne rozwiązanie',
    resolutionFinal: 'Ostateczne rozwiązanie',
    nextPhase: 'Przejdź dalej',
    submit: 'Wyślij',
    sendMessage: 'Wyślij',
    submitted: 'Wysłano',
    waitingForPartner: 'Czekamy na partnera...',
    partnerSubmitted: 'Partner przesłał swoją odpowiedź',
  },
  ai: {
    mediatorTitle: 'AI Mediator',
    mediatorName: 'Most AI',
    thinking: 'Mediator analizuje...',
    askMediator: 'Zapytaj mediatora',
    question: 'Zadaj pytanie mediatorowi',
    questionPlaceholder: 'Np. "Jak mogę lepiej wyrazić swoje potrzeby?"',
    send: 'Wyślij',
    suggestion: 'Sugestia mediatora',
    tip: 'Wskazówka',
    question_label: 'Pytanie',
    noMessages: 'Zacznij rozmowę z mediatorem',
  },
  premium: {
    title: 'Most Premium',
    sub: 'Nieograniczone spory i pełna historia',
    feature1: 'Nieograniczone spory z partnerem',
    feature2: 'Historia wszystkich sporów',
    feature3: 'Zaawansowane statystyki pary',
    feature4: 'Priorytetowe wsparcie AI',
    feature5: 'Eksport raportów PDF',
    feature6: 'OCR — analiza zrzutów ekranu',
    weekly: 'Tygodniowo',
    monthly: 'Miesięcznie',
    yearly: 'Rocznie',
    weeklyPrice: '14,99 zł/tydz.',
    monthlyPrice: '49,99 zł/mies.',
    yearlyPrice: '399,99 zł/rok',
    yearlySave: 'Oszczędzasz 200 zł',
    subscribe: 'Subskrybuj Premium',
    restore: 'Przywróć zakupy',
    current: 'Twój plan',
    free: 'Free',
    freeSub: '3 spory miesięcznie',
    premium: 'Premium',
    premiumSub: 'Nieograniczone spory',
    mock: 'DEMO — płatności wkrótce',
    soloTitle: 'Analiza Solo',
    soloDesc: 'Jednorazowa analiza bez partnera — 9,99 zł',
    paymentMethods: 'App Store · Google Play',
  },
  solo: {
    title: 'Analiza Solo',
    subtitle: 'Zrozum konflikt samodzielnie',
    price: '9,99 zł',
    priceDesc: 'Jednorazowy zakup · Bez subskrypcji',
    buy: 'Kup Analizę Solo — 9,99 zł',
    situationLabel: 'Opisz sytuację',
    situationPlaceholder: 'Co się stało? Jak wygląda konflikt z Twojej perspektywy?',
    feelingsLabel: 'Jak się czujesz?',
    needsLabel: 'Czego potrzebujesz?',
    analyze: 'Analizuj z AI',
    screenshotLabel: 'Wgraj zrzut rozmowy (OCR)',
    ready: 'Analiza gotowa',
    suggestions: 'Sugestie do rozmowy:',
  },
  profile: {
    title: 'Profil',
    settings: 'Ustawienia',
    myProfile: 'Mój profil',
    partner: 'Partner',
    plan: 'Plan',
    disputeStats: 'Statystyki sporów',
    totalDisputes: 'Wszystkie spory',
    resolved: 'Rozwiązane',
    active: 'Aktywne',
    successRate: 'Wskaźnik sukcesu',
    editProfile: 'Edytuj profil',
    notifications: 'Powiadomienia',
    privacy: 'Prywatność',
    help: 'Pomoc',
    logout: 'Wyloguj się',
    logoutConfirm: 'Czy na pewno chcesz się wylogować?',
    cancel: 'Anuluj',
    confirm: 'Wyloguj',
    disconnectCouple: 'Rozłącz parę',
    disconnectConfirm: 'Czy na pewno chcesz rozłączyć parę?',
    version: 'Wersja',
  },
  common: {
    back: 'Wróć',
    next: 'Dalej',
    cancel: 'Anuluj',
    save: 'Zapisz',
    delete: 'Usuń',
    edit: 'Edytuj',
    done: 'Gotowe',
    close: 'Zamknij',
    loading: 'Ładowanie...',
    error: 'Błąd',
    success: 'Sukces',
    ok: 'OK',
    yes: 'Tak',
    no: 'Nie',
    required: 'Pole wymagane',
    or: 'lub',
    free: 'Darmowy',
    premium: 'Premium',
    new: 'Nowy',
  },
};
